RunFactorial : Factorial.o FactorialFunc.o
	gcc -o RunFactorial Factorial.o FactorialFunc.o
Factorial.o : Factorial.c facto.h
	gcc -c Factorial.c

FactorialFunc.o : FactorialFunc.c facto.h
	gcc -c FactorialFunc.c
